// <auto-generated />
using DataBaseLayout;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataBaseLayout.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataBaseLayout.Models.Brand", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("DataBaseLayout.Models.Feature", b =>
                {
                    b.Property<int>("Name")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Name"));

                    b.Property<string>("HTMLFlag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("DataBaseLayout.Models.Perfume", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerfumeCategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<double>("RatingAppearance")
                        .HasColumnType("float");

                    b.Property<double>("RatingIntension")
                        .HasColumnType("float");

                    b.Property<double>("RatingPersistence")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandName");

                    b.HasIndex("PerfumeCategoryName");

                    b.ToTable("Perfumes");
                });

            modelBuilder.Entity("DataBaseLayout.Models.PerfumeCategory", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("PerfumeCategories");
                });

            modelBuilder.Entity("DataBaseLayout.Models.PerfumeImage", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerfumeId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PerfumeId");

                    b.ToTable("PerfumeImages");
                });

            modelBuilder.Entity("DataBaseLayout.Models.Promotion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("DataBaseLayout.Models.Review", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerfumeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PerfumeId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("DataBaseLayout.Models.ReviewConversation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ReviewId");

                    b.HasIndex("UserId");

                    b.ToTable("ReviewConversations");
                });

            modelBuilder.Entity("DataBaseLayout.Models.ShoppingCartPerfume", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PerfumeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PerfumeId");

                    b.HasIndex("UserId");

                    b.ToTable("ShoppingCartPerfumes");
                });

            modelBuilder.Entity("Delivery", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("DeliveryPerfume", b =>
                {
                    b.Property<string>("DeliveriesName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PerfumesId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("DeliveriesName", "PerfumesId");

                    b.HasIndex("PerfumesId");

                    b.ToTable("DeliveryPerfume");
                });

            modelBuilder.Entity("FeatureRole", b =>
                {
                    b.Property<int>("FeaturesName")
                        .HasColumnType("int");

                    b.Property<string>("RolesName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FeaturesName", "RolesName");

                    b.HasIndex("RolesName");

                    b.ToTable("FeatureRole");
                });

            modelBuilder.Entity("Role", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Wish", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PerfumeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PerfumeId");

                    b.HasIndex("UserId");

                    b.ToTable("WishList");
                });

            modelBuilder.Entity("DataBaseLayout.Models.Perfume", b =>
                {
                    b.HasOne("DataBaseLayout.Models.Brand", "Brand")
                        .WithMany("Perfumes")
                        .HasForeignKey("BrandName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataBaseLayout.Models.PerfumeCategory", "PerfumeCategory")
                        .WithMany("Perfumes")
                        .HasForeignKey("PerfumeCategoryName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("PerfumeCategory");
                });

            modelBuilder.Entity("DataBaseLayout.Models.PerfumeImage", b =>
                {
                    b.HasOne("DataBaseLayout.Models.Perfume", "Perfume")
                        .WithMany("PerfumeImages")
                        .HasForeignKey("PerfumeId");

                    b.Navigation("Perfume");
                });

            modelBuilder.Entity("DataBaseLayout.Models.Review", b =>
                {
                    b.HasOne("DataBaseLayout.Models.Perfume", "Perfume")
                        .WithMany("Reviews")
                        .HasForeignKey("PerfumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId");

                    b.Navigation("Perfume");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataBaseLayout.Models.ReviewConversation", b =>
                {
                    b.HasOne("DataBaseLayout.Models.Review", "Review")
                        .WithMany("ReviewConversations")
                        .HasForeignKey("ReviewId");

                    b.HasOne("User", "User")
                        .WithMany("ReviewConversations")
                        .HasForeignKey("UserId");

                    b.Navigation("Review");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataBaseLayout.Models.ShoppingCartPerfume", b =>
                {
                    b.HasOne("DataBaseLayout.Models.Perfume", "Perfume")
                        .WithMany("ShoppingCartPerfumes")
                        .HasForeignKey("PerfumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("ShoppingCartPerfumes")
                        .HasForeignKey("UserId");

                    b.Navigation("Perfume");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DeliveryPerfume", b =>
                {
                    b.HasOne("Delivery", null)
                        .WithMany()
                        .HasForeignKey("DeliveriesName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataBaseLayout.Models.Perfume", null)
                        .WithMany()
                        .HasForeignKey("PerfumesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FeatureRole", b =>
                {
                    b.HasOne("DataBaseLayout.Models.Feature", null)
                        .WithMany()
                        .HasForeignKey("FeaturesName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Role", null)
                        .WithMany()
                        .HasForeignKey("RolesName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("User", b =>
                {
                    b.HasOne("Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleName");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Wish", b =>
                {
                    b.HasOne("DataBaseLayout.Models.Perfume", "Perfume")
                        .WithMany("Wishes")
                        .HasForeignKey("PerfumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("Wishes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfume");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DataBaseLayout.Models.Brand", b =>
                {
                    b.Navigation("Perfumes");
                });

            modelBuilder.Entity("DataBaseLayout.Models.Perfume", b =>
                {
                    b.Navigation("PerfumeImages");

                    b.Navigation("Reviews");

                    b.Navigation("ShoppingCartPerfumes");

                    b.Navigation("Wishes");
                });

            modelBuilder.Entity("DataBaseLayout.Models.PerfumeCategory", b =>
                {
                    b.Navigation("Perfumes");
                });

            modelBuilder.Entity("DataBaseLayout.Models.Review", b =>
                {
                    b.Navigation("ReviewConversations");
                });

            modelBuilder.Entity("Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("ReviewConversations");

                    b.Navigation("Reviews");

                    b.Navigation("ShoppingCartPerfumes");

                    b.Navigation("Wishes");
                });
#pragma warning restore 612, 618
        }
    }
}
